/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.test;

import java.util.Scanner;

public class App {
    public String getGreeting() {
      Scanner scanner = new Scanner(System.in);


      int c = scanner.nextInt();
      int arr[] = new int[c];
      
      for (int i = 0; i < c; i++)  {
        int A = scanner.nextInt();
        int B = scanner.nextInt();
        arr[c] = A + B;
    }

    for (int i : arr) {
        System.out.println(c);
    }

      scanner.close();
    }
}
